"""
Configuration loader for autoexport.

Reads from `autoexport.toml` (preferred) or `pyproject.toml` [tool.autoexport].

Example autoexport.toml:

    [autoexport]
    watch = ["app/models", "app/services", "app/controllers"]
    exclude_dirs = ["__pycache__", "tests", ".git"]
    exclude_files = ["conftest.py", "setup.py"]
    mode = "all"                    # "all" | "public" | "decorated"
    import_style = "relative"       # "relative" | "absolute"
    export_constants = true
    export_variables = false
    flatten = false
    lazy = false
    use_black = false
    header = "# Auto-generated by autoexport — do not edit manually"
    recursive = true
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore
        except ImportError:
            tomllib = None  # type: ignore


class ExportMode(Enum):
    ALL = "all"
    """Export all top-level public classes, functions, and constants."""

    PUBLIC = "public"
    """Export classes and functions only (no constants/variables)."""

    DECORATED = "decorated"
    """Only export items marked with @export decorator."""


class ImportStyle(Enum):
    RELATIVE = "relative"
    """Use relative imports: from .module import Name"""

    ABSOLUTE = "absolute"
    """Use absolute imports: from package.module import Name"""


@dataclass
class Config:
    """Autoexport configuration."""

    watch: list[str] = field(default_factory=lambda: ["."])
    """Directories to watch for changes."""

    exclude_dirs: list[str] = field(
        default_factory=lambda: ["__pycache__", ".git", ".venv", "venv",
                                  "node_modules", ".mypy_cache", ".pytest_cache"]
    )
    """Directory names to skip."""

    exclude_files: list[str] = field(
        default_factory=lambda: ["conftest.py", "setup.py"]
    )
    """File names to skip."""

    mode: ExportMode = ExportMode.ALL
    """Which symbols to export."""

    import_style: ImportStyle = ImportStyle.RELATIVE
    """Import style: relative (from .x import Y) or absolute (from pkg.x import Y)."""

    export_constants: bool = True
    """Whether to export UPPER_CASE constants."""

    export_variables: bool = False
    """Whether to export regular (non-constant) top-level variables."""

    flatten: bool = False
    """Bubble up child package exports to parent __init__.py."""

    lazy: bool = False
    """Generate PEP 562 lazy imports (__getattr__ + __dir__) instead of eager imports."""

    use_black: bool = False
    """Format generated __init__.py files with black."""

    header: str = "# Auto-generated by autoexport — do not edit manually"
    """Header comment for generated __init__.py files."""

    recursive: bool = True
    """Whether to recurse into subdirectories."""

    export_decorator: str = "export"
    """Name of the decorator that marks explicit exports (for 'decorated' mode)."""

    respect_existing_all: bool = True
    """If a file defines __all__, use that instead of auto-detecting."""

    @property
    def watch_paths(self) -> list[Path]:
        return [Path(p) for p in self.watch]


def load_config(config_path: Optional[Path] = None) -> Config:
    """
    Load configuration from file.

    Search order:
        1. Explicit path (if given)
        2. autoexport.toml in current directory
        3. pyproject.toml [tool.autoexport] in current directory
        4. Defaults
    """
    if config_path is not None:
        return _load_from_file(config_path)

    # Try autoexport.toml
    ae_toml = Path("autoexport.toml")
    if ae_toml.exists():
        return _load_from_file(ae_toml)

    # Try pyproject.toml
    pp_toml = Path("pyproject.toml")
    if pp_toml.exists():
        return _load_from_file(pp_toml, section="tool")

    # Defaults
    return Config()


_SIMPLE_BOOL_KEYS = [
    "export_constants", "export_variables", "flatten", "lazy",
    "use_black", "recursive", "respect_existing_all",
]

_SIMPLE_STR_KEYS = ["header", "export_decorator"]

_SIMPLE_LIST_KEYS = ["watch", "exclude_dirs", "exclude_files"]


def _load_from_file(path: Path, section: Optional[str] = None) -> Config:
    """Load config from a TOML file."""
    if tomllib is None:
        print("Warning: tomllib/tomli not available, using defaults.", flush=True)
        return Config()

    text = path.read_bytes()
    data = tomllib.loads(text.decode("utf-8"))

    if section:
        data = data.get(section, {})

    ae_data = data.get("autoexport", {})
    if not ae_data:
        return Config()

    config = Config()

    for key in _SIMPLE_LIST_KEYS:
        if key in ae_data:
            setattr(config, key, ae_data[key])

    for key in _SIMPLE_STR_KEYS:
        if key in ae_data:
            setattr(config, key, ae_data[key])

    for key in _SIMPLE_BOOL_KEYS:
        if key in ae_data:
            setattr(config, key, ae_data[key])

    if "mode" in ae_data:
        config.mode = ExportMode(ae_data["mode"])

    if "import_style" in ae_data:
        config.import_style = ImportStyle(ae_data["import_style"])

    return config
