"""
Configuration loader for autoexport.

Reads from `autoexport.toml` (preferred) or `pyproject.toml` [tool.autoexport].

Example autoexport.toml:

    [autoexport]
    watch = ["app/models", "app/services", "app/controllers"]
    exclude_dirs = ["__pycache__", "tests", ".git"]
    exclude_files = ["conftest.py", "setup.py"]
    mode = "all"                    # "all" | "public" | "decorated"
    export_constants = true
    export_variables = false
    header = "# Auto-generated by autoexport — do not edit manually"
    recursive = true
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore
        except ImportError:
            tomllib = None  # type: ignore


class ExportMode(Enum):
    ALL = "all"
    """Export all top-level public classes, functions, and constants."""

    PUBLIC = "public"
    """Export classes and functions only (no constants/variables)."""

    DECORATED = "decorated"
    """Only export items marked with @export decorator."""


@dataclass
class Config:
    """Autoexport configuration."""

    watch: list[str] = field(default_factory=lambda: ["."])
    """Directories to watch for changes."""

    exclude_dirs: list[str] = field(
        default_factory=lambda: ["__pycache__", ".git", ".venv", "venv",
                                  "node_modules", ".mypy_cache", ".pytest_cache"]
    )
    """Directory names to skip."""

    exclude_files: list[str] = field(
        default_factory=lambda: ["conftest.py", "setup.py"]
    )
    """File names to skip."""

    mode: ExportMode = ExportMode.ALL
    """Which symbols to export."""

    export_constants: bool = True
    """Whether to export UPPER_CASE constants."""

    export_variables: bool = False
    """Whether to export regular (non-constant) top-level variables."""

    header: str = "# Auto-generated by autoexport — do not edit manually"
    """Header comment for generated __init__.py files."""

    recursive: bool = True
    """Whether to recurse into subdirectories."""

    export_decorator: str = "export"
    """Name of the decorator that marks explicit exports (for 'decorated' mode)."""

    respect_existing_all: bool = True
    """If a file defines __all__, use that instead of auto-detecting."""

    @property
    def watch_paths(self) -> list[Path]:
        return [Path(p) for p in self.watch]


def load_config(config_path: Optional[Path] = None) -> Config:
    """
    Load configuration from file.

    Search order:
        1. Explicit path (if given)
        2. autoexport.toml in current directory
        3. pyproject.toml [tool.autoexport] in current directory
        4. Defaults
    """
    if config_path is not None:
        return _load_from_file(config_path)

    # Try autoexport.toml
    ae_toml = Path("autoexport.toml")
    if ae_toml.exists():
        return _load_from_file(ae_toml)

    # Try pyproject.toml
    pp_toml = Path("pyproject.toml")
    if pp_toml.exists():
        return _load_from_file(pp_toml, section="tool")

    # Defaults
    return Config()


def _load_from_file(path: Path, section: Optional[str] = None) -> Config:
    """Load config from a TOML file."""
    if tomllib is None:
        print("Warning: tomllib/tomli not available, using defaults.", flush=True)
        return Config()

    text = path.read_bytes()
    data = tomllib.loads(text.decode("utf-8"))

    if section:
        data = data.get(section, {})

    ae_data = data.get("autoexport", {})
    if not ae_data:
        return Config()

    config = Config()

    if "watch" in ae_data:
        config.watch = ae_data["watch"]
    if "exclude_dirs" in ae_data:
        config.exclude_dirs = ae_data["exclude_dirs"]
    if "exclude_files" in ae_data:
        config.exclude_files = ae_data["exclude_files"]
    if "mode" in ae_data:
        config.mode = ExportMode(ae_data["mode"])
    if "export_constants" in ae_data:
        config.export_constants = ae_data["export_constants"]
    if "export_variables" in ae_data:
        config.export_variables = ae_data["export_variables"]
    if "header" in ae_data:
        config.header = ae_data["header"]
    if "recursive" in ae_data:
        config.recursive = ae_data["recursive"]
    if "export_decorator" in ae_data:
        config.export_decorator = ae_data["export_decorator"]
    if "respect_existing_all" in ae_data:
        config.respect_existing_all = ae_data["respect_existing_all"]

    return config
